### ISSUE TITLE
Errors launching

### ISSUE THREAD

**Issue by eo1989** [piquette/edgr#1]
Hi, Im attempting to test out your app (having used qtrn for quick quotes, i appreciate the time you've put into these), but upon launching it with edgr init I get:

INFO[0000] connecting to postgres..
WARN[0000] dial tcp [::1]:5432: connect: connection refused

So I tried "brew services start postgresql" first, then entered "edgr init" once again, only for a different error to pop up:

INFO[0000] connecting to postgres..
WARN[0000] FATAL #28000 role "postgres" does not exist

running macOS Catalina 10.15.4 on a MBPr from early 2013, homebrew is up to date (cleanup/doctor show no errors or issues relating to either postgresql nor edgr)

**Comment by ackleymi** [comment]
@eo1989  ah, I think youre missing the default database in the postgresql service, the default is named 'postgres', I think. As a side note, docker on a mac makes this easy to test drive :) Let me know
